version: '3.8'

services:
  meu-projeto-web:
    build:
      context: ./frontend
    container_name: meu-projeto-web
    ports:
      - "80:80"
    depends_on:
      - meu-projeto-api
    networks:
      - blocktex-net

  meu-projeto-api:
    build:
      context: ./backend
    container_name: meu-projeto-api
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - blocktex-data:/app/data
    networks:
      - blocktex-net

networks:
  blocktex-net:
    driver: bridge

volumes:
  blocktex-data:
